version: "3.4"
services:
    apt_mirror:
        build: ubuntu-22.04-apt-mirror
        profiles:
         - donotstart

    repo_nginx:
        build: ubuntu-22.04-repo-nginx
        restart: unless-stopped
        volumes:
         - type: bind
           source: /mnt/data-ext4-int/ubuntu-22.04-mirror
           target: /srv/http
        ports:
         - 80:80

    devpisrv:
        build: pypimirror
        ports:
         - "${SERVER_IP:-0.0.0.0}:${SERVER_PORT:-3141}:3141"
        volumes:
         - devpisrv-data:/var/local/devpisrv
        restart: always
        #profiles:
        # - donotstart

volumes:
    devpisrv-data:



